scenario_cfg:
  dataset_name: FSC147
  base_data_path: data/datasets/LAMM/2D_Benchmark
  ppl_cfg: 
    heatmap_width: 2

eval_cfg:
  instruction_cfg:
    query_type: standard_query
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 32
  metric_cfg:
    metric_type: basic
    inference_type: ppl