scenario_cfg:
  dataset_name: FSC147
  base_data_path: data/datasets/LAMM/2D_Benchmark

eval_cfg:
  instruction_cfg:
    query_type: standard_query
  inferencer_cfg:
    inferencer_type: Direct
    max_new_tokens: 256
    batch_size: 32
  metric_cfg:
    metric_type: basic
    inference_type: direct