scenario_cfg:
  dataset_name: CIFAR10
  base_data_path: /mnt/petrelfs/shizhelun/shizhelun/data/datasets/LAMM/2D_Benchmark
  ppl: True
eval_cfg:
  instruction_cfg: 
    prompt_type: standard_query
    incontext_cfg:
      retriever_type: topk_image
      ice_num: 3
      use_pic: False
      add_sysmsg: True
      sysmsg: 'You will now see some examples. The example has no relation to the provided image content. You need to follow the example and answer the final question based on the image content.'
      mult_conversations: False
      random_seed: 1
  inferencer_cfg:
    inferencer_type: ICL_PPL
    batch_size: 8
  metric_cfg:
    metric_type: basic