scenario_cfg:
  dataset_name: ScienceQA
  base_data_path: data/datasets/LAMM/2D_Benchmark
  ppl: True
  option_content: False

eval_cfg:
  instruction_cfg: 
    query_type: standard_query
    incontext_cfg:
      ice_with_image: False
      retriever_type: random
      ice_num: 3
      random_seed: 1
  inferencer_cfg:
    inferencer_type: ICL_PPL
    batch_size: 4
    CoT: True
    max_new_tokens: 256
  metric_cfg:
    metric_type: basic