scenario_cfg:
  dataset_name: POPE_COCO_adversarial
  base_data_path: data/datasets/coco
  ppl: True
  option_content: False

eval_cfg:
  instruction_cfg: 
    query_type: standard_query
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 8
    CoT: True
    max_new_tokens: 256
  metric_cfg:
    metric_type: Hallucination
