scenario_cfg:
  dataset_name: VOC2012
  base_data_path: data/datasets/LAMM/2D_Benchmark
  ppl_cfg:
    negative_opt_num: 3
    random_seed: 0
   
eval_cfg:
  instruction_cfg:
    query_type: multiturn
    query_assigned_ids: 2
    template_assigned_ids: 2
  inferencer_cfg:
    inferencer_type: Det
    max_new_tokens: 512
    batch_size: 8
  metric_cfg:
    metric_type: KOSMOS