scenario_cfg:
  dataset_name: SEEDBench
  base_data_path: data/datasets/SEED-Bench

eval_cfg:
  instruction_cfg: 
    query_type: query_pool
    prompt_assigned_ids: 4
    template_assigned_ids: 0
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 8
  metric_cfg:
    metric_type: basic